package com.quzzar.villagelife.entities;

import java.util.List;

/**
 * The villager skin pools, one list of content-hash filenames per gender.
 *
 * <p>GENERATED by {@code scratchpad/build_skins.py} from the curated skin set --
 * do not edit by hand. Each entry is the sha256[:16] of a
 * {@code textures/entity/person/<hash>.png} file; identical skins share a hash and
 * so appear once. A villager renders {@code pool.get(skinVariant % pool.size())}
 * from its own gender's list, so a man draws a man's skin and a woman a woman's.
 */
public final class PersonSkins {

  private PersonSkins() {
  }

  public static final List<String> MALE = List.of(
      "026523315ff8abfa", "0afca8d7f7b37a97", "1108b08011113e68", "11e2d54557e6a029", "1270e2f56d4ba409", "1fdf4c9d460aa68f", "258b94d412bff2f0", "26c8abd41d8d6df8", "2b167116bc590378", "306dd802281c0d7b", "3a864b06b76f8f02", "4680ca600fc8bcf4", "4969775abbbe6f34", "49bfb17fabc3f930", "5679940eeec05f3f", "572bee31902bf68a", "576f02e50b23d8e6", "601327d17a08c772", "6696a200eb0fa7c0", "6a2076d473ea7556", "6cd5a50aaf9cc0ca", "72d94ee877994fce", "7660f601d9bb2e16", "7c62fdc352413eaf", "81971a76fc6e9ac8", "839102b0136eb667", "86c3a047435c241c", "87f0d8faf218afa0", "88c4ea273314dd58", "89066de2dac196b0", "8d357bd4ca23f5c8", "916935edee9f7959", "a10447b4993b7c8b", "a449d0dff837b6ef", "b3cda2ff32262fad", "b9225abb765e1deb", "ba15a4a9cbacf3cc", "c05c17b81b52ad6e", "c143b822e0b24949", "c34abeabd2ca7cff", "c35a9feb12695abe", "cf44d8d3e79b7eb4", "d379deb08a03fb94", "d68008027a0a873f", "dbc5655269e17dd2", "dd0d46b56121e36d", "dd37a89ddea770b3", "e8fad6bce91ee35f", "e9325cd119b7a1eb", "e9a2cda01fbfa70c", "f43f0134d55175e8", "f4e886aa5e47eeb0", "fc9a3e7a991f5bb1");

  public static final List<String> FEMALE = List.of(
      "0887fd342f0b9247", "0fe33eb202736edb", "12cacc893bff3c65", "157dda53cb72b82a", "204c77188e745576", "24eea1668da63a6d", "30f7aaac22e139db", "50cde87dce4a7dcf", "544f28f1bfb32eae", "55be7c4637aabce7", "59f0e0d634a3cd65", "6042986a69db0168", "73a39d60e23d2073", "782889f0fca9e472", "86e305b544466765", "9449996658bf56b1", "96addc6ad7f9a900", "9826de29980724b6", "985f391fb0924e20", "9a73ff7d3333c348", "aab41112c86b5e95", "aeb4c347ae4e9332", "af7c01fe5d5cd600", "c01a411da7fc693b", "c21bd075d59897d8", "c2467fe6f1756b55", "d4a0a13640b481fa", "e0a710cd5cb08cf3", "f32c2df3f3db796a", "f64bf7dbcef9703d", "ff13297a1f81c303");

  public static final List<String> NONBINARY = List.of(
      "6d4716178677e996", "8ea41bff3449f17b", "c3699c81218b4555", "d5b145de9663305c", "e706f556ee4c86cc");

  /** The skin-hash pool for the given gender. */
  public static List<String> forGender(Gender gender) {
    return switch (gender) {
      case MALE -> MALE;
      case FEMALE -> FEMALE;
      case NONBINARY -> NONBINARY;
    };
  }
}
